apiVersion: v1
kind: ConfigMap
metadata:
  name: foodfast-config
  namespace: foodfast
data:
  NODE_ENV: "production"
  
  # RabbitMQ Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  
  # Database Hosts
  USER_DB_HOST: "userdb"
  PRODUCT_DB_HOST: "productdb"
  ORDER_DB_HOST: "orderdb"
  PAYMENT_DB_HOST: "paymentdb"
  DB_PORT: "5432"
  
  # Service Ports
  API_GATEWAY_PORT: "8743"
  USER_SERVICE_PORT: "3001"
  PRODUCT_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
  PAYMENT_SERVICE_PORT: "3004"
  EMAIL_SERVICE_PORT: "3005"
  SOCKET_GATEWAY_PORT: "4000"
  
  # Internal Service URLs
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  PAYMENT_SERVICE_URL: "http://payment-service:3004"
  EMAIL_SERVICE_URL: "http://email-service:3005"
  SOCKET_GATEWAY_URL: "http://socket-gateway:4000"
